#!/bin/sh

origDir=`pwd`

direc=$1

cd $direc

baseT1="T1"

if [ -d T1/unusable ] ; then
    baseT1="T1/unusable"
fi

if [ -f QC_files/T1/QC_be/T1_not_defaced.nii.gz ] ; then

    # Second result
    if [ ! -f QC_files/T1/QC_be/T1_brain_mask_freesurfer_2.nii.gz ] ; then
        mri_watershed QC_files/T1/QC_be/T1_not_defaced.nii.gz $baseT1/grot_FS_mask_2.nii.gz  >/dev/null

        #Try different parameters if the default configuration failed
        if [ ! -f $baseT1/grot_FS_mask_2.nii.gz ] ; then 
            mri_watershed -h 20 QC_files/T1/QC_be/T1_not_defaced.nii.gz $baseT1/grot_FS_mask_2.nii.gz >/dev/null
            
            if [ ! -f $baseT1/grot_FS_mask_2.nii.gz ] ; then 
                mri_watershed -h 10 QC_files/T1/QC_be/T1_not_defaced.nii.gz $baseT1/grot_FS_mask_2.nii.gz >/dev/null
            fi 
        fi 

        fslmaths $baseT1/grot_FS_mask_2.nii.gz -thr 0.5 -bin QC_files/T1/QC_be/T1_brain_mask_freesurfer_2.nii.gz
    fi

fi

rm $baseT1/grot*.*    
cd $origDir

